// <auto-generated />
namespace Sport.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_StateDeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_StateDeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201911230756251_Change_StateDeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
